server:
  port: 3002

spring:
  application:
    name: order-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3150/eureka/